---
title: "Nyckelharpa Origins"
author: "Genelle Denzin"
date: "March 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

## Nyckelharpa Origins

```{r}
library(leaflet)
library(tidyverse)
library(htmlwidgets)
library(rvest)
library(readxl)
library(mapview)

x <- read_xlsx("NyckelharpaHistoryData.xlsx") %>%
  arrange(DatesBackTo)

image75 <- popupImage(x$Localimage, 
                      src = "local", 
                      width = "200px", 
                      height = "100%")

origins <- leaflet(x) %>%
  setView(lng = 16.5, lat = 57, zoom = 3.5) %>%
  addProviderTiles("Esri.NatGeoWorldMap") %>%
  addCircleMarkers(
    lng = ~ Longitude,
    lat = ~ Latitude,
    popup = paste0(
      "<div style=\"background-color: #fff; padding: 8px;\"><h3><b>Dates Back To ",
      x$DatesBackTo,
      "</b></h3><div>",
      x$Description,
      "</div><br>",
      image75,
      "</div><div style=\"background-color: #fff; padding: 8px; \"><small>Photo:",
      x$Attribution,
      "</small></div>"
    ), 
    group = x$DatesBackTo
  ) %>%
  addLayersControl(overlayGroups = x$DatesBackTo,
                   options = layersControlOptions(collapsed = FALSE))
saveWidget(origins, "NyckelharpaOrigins.html", title = "Nyckelharpa Origins")
```

